<?php
/**
 * | AndPHP框架[基于ThinkPHP5开发]
 * +----------------------------------------------------------------------
 * | Copyright (c) 2017-2019 http://www.andphp.com
 * +----------------------------------------------------------------------
 * | AndPHP承诺基础框架永久免费开源，您可用于学习和商用，但必须保留软件版权信息。
 * +----------------------------------------------------------------------
 * | author    :BabySeeME <417170808@qq.com>
 * +----------------------------------------------------------------------
 * | createTime :2018/3/1 000121:12
 * +----------------------------------------------------------------------
 */

namespace app\common\controller;
use app\common\model\Module as ModuleModel;


/**
 * 默认前台公用基础控制器
 * +----------------------------------------------------------------------
 * Class HomeBase
 * @package app\common\controller
 * +----------------------------------------------------------------------
 * | author     :BabySeeME <417170808@qq.com>
 * +----------------------------------------------------------------------
 * | createTime :2018-03-01 21:12
 */
class IndexBase extends AppBase
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $module=request()->module();
        $status=(new ModuleModel())->where(['name'=>$module])->value('status');
        if($status == 0){
            $this->error('你访问的地址不存在,<br/> 正在为你跳转。。。',config('app.default_module').'/index/index');
        }
    }

}