<?php
/**
 * | AndPHP框架[基于ThinkPHP5开发]
 * +----------------------------------------------------------------------
 * | Copyright (c) 2017-2019 http://www.andphp.com
 * +----------------------------------------------------------------------
 * | AndPHP承诺基础框架永久免费开源，您可用于学习和商用，但必须保留软件版权信息。
 * +----------------------------------------------------------------------
 * | author    :BabySeeME <417170808@qq.com>
 * +----------------------------------------------------------------------
 * | createTime :2018/3/10 001020:37
 * +----------------------------------------------------------------------
 */

namespace app\common\controller;



use think\facade\Session;

class UserController extends AppController
{



    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub


        $this->checkAuth('user','/user/login/index');

        $nav=[];
        $this->assign('nav', $nav);
        $this->assign('default_index',config('app.default_module'));
    }


}